services:
  client:
    image: "cetech/fibonacci-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "cetech/fibonacci-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PGUSER
      - PG_HOST=$PGHOST
      - PG_DATABASE=$PGDATABASE
      - PG_PASSWORD=$PGPASSWORD
      - PG_PORT=$PGPORT
  worker:
    image: "cetech/fibonacci-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "cetech/fibonacci-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
